### PR TITLE
Optimize class path scanning.

### PR DESCRIPTION
**Pull request by CamilYed**
Please review my solution.

### CODE REVIEW

**Comment by CamilYed** [comment]
BUILD FAILED in 8s
2 actionable tasks: 1 executed, 1 up-to-date
The command "if [ $OSSRH_PASSWORD != "false" ] && cat gradle.properties | grep -q SNAPSHOT; then
  ./gradlew clean build alljavadoc uploadArchives jacocoRootReport copySource coveralls -PnexusUsername="${OSSRH_USERNAME}" -PnexusPassword="${OSSRH_PASSWORD}" -Psigning.keyId="" -Psigning.password=""
else
  ./gradlew check jacocoRootReport copySource coveralls

**Comment by Clayton7510** [comment]
You've got a few static code analysis errors. Please fix the build and then I'm happy to check it out.

**Comment by Clayton7510** [comment]
There are static code analysis failures as stated above, which have not been fixed. However, think you're PR suggests a worthwhile update. So, I'll keep it on deck. And after the release of v0.12, I'll add it to another branch, correct the errors and merge it in to the develop branch. I'll also give you credit as a contributor and add you to the commit log as an author. It will show both of us on the commit. But I guess that's fair since I am fixing the failed build - so, it's a little more work for me ;)

**Review by Clayton7510 — CHANGES_REQUESTED** [review]
Build failures need to be corrected.

**Pull request closed without merging**
