### PR TITLE
POJO RuleChain should stop if STOP_ON_FAILURE is set as ruleChainAction

### LINKED ISSUE #159: STOP_ON_FAILURE not working for POJO rules
I am using version 0.11 and the STOP_ON_FAILURE  is not working for POJO rules.  I created a simple rule to validate, see below.  When the exception is thrown, not only does the next rule in the chain execute but the auditor marks it as executed.

@Rule(order = 2, ruleChainAction = RuleChainActionType.STOP_ON_FAILURE)
public class Rule2 {

	@Given("myInput")
	private String input;

	@Result
	private String result;

	@When
	public boolean when() {
		if (true) {
			throw new NullPointerException();
		}
		return true;
	}

	@Then
	public RuleState then() {
		result = "success";
		return RuleState.BREAK;
	}

}

### PR DESCRIPTION
**Pull request by mikelear**
This should fix #159 , if an Exception is thrown we have a RuleStatus of EXCEPTION, we set this on the Exception handling.
I think this is how the RuleChain should work but would appreciate any feedback

### CODE REVIEW

**Comment by mikelear** [comment]
Changed some logic to handle the new ERROR status and added some more tests

**Comment by mikelear** [comment]
Added a lot more tests to check for the execution of POJO rules.
For instance if you set a BREAK in the then() but have set STOP_ON_FAILURE it won't stop, this is the current execution and I've left it like that but added a Test to show this (and quiet a few more POJO tests as there isn't as many as there are for RuleBuilder logic)
This fix mainly STOPS/ERRORS (RuleException) correctly when there is an EXCEPTION in when ( as the #159 was originally opened for) and then adds the Tests to who that and other POJO scenarios.

**Comment by Clayton7510** [comment]
Thanks for the contribution!

**Comment by mikelear** [comment]
my pleasure , thanks for checking

**Pull request merged**
